AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ''

Resources:
    HelloWorld:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'hello-world'
            Description: ''
            CodeUri: .
            Handler: main-action.php
            Timeout: 10 # Timeout in seconds
            MemorySize: 1024 # The memory size is related to the pricing and CPU power
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:us-east-2:209497400698:layer:php-73:1'
